repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: end-of-file-fixer          # Ensures files end with newline
      - id: trailing-whitespace        # Removes trailing whitespace
      - id: mixed-line-ending          # Ensures consistent line endings
        args: [--fix=lf]
      - id: check-added-large-files    # Prevents large files from being committed

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.13.0
    hooks:
      - id: ruff
        args: [--fix]
        files: ^(src/|tests/)
      - id: ruff-format
        files: ^(src/|tests/)
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.18.1
    hooks:
      - id: mypy
        files: ^src/
        additional_dependencies: [
          types-requests,
          types-setuptools,
        ]
