name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12"]

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v4
        with:
          enable-cache: true
          cache-dependency-glob: "uv.lock"

      - name: Set up Python ${{ matrix.python-version }}
        run: uv python install ${{ matrix.python-version }}

      - name: Install the project
        run: uv sync --all-extras --dev

      - name: Run linter
        run: uv tool run ruff check src/ tests/

      - name: Check formatting
        run: uv tool run ruff format src/ tests/ --check

      - name: Run type checker
        run: uv tool run mypy src/

      - name: Run tests
        run: uv run pytest --verbose

      - name: Test server startup
        run: |
          uv run uvicorn src.main:app --host 0.0.0.0 --port 8000 &
          SERVER_PID=$!
          sleep 5
          curl -f http://localhost:8000/ || exit 1
          kill $SERVER_PID