name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      # Ensure terminology matches tests (e.g., placeholder expects "Pizza-1, Pizza-2")
      OBJECT_NAME_SINGULAR: pizza
      PROPERTY_NAME_SINGULAR: topping
      # Database configuration for tests
      DATABASE_URL: postgresql://savt_user:savt_password@localhost:5432/savt_test
      TEST_DATABASE: postgresql

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: savt_user
          POSTGRES_PASSWORD: savt_password
          POSTGRES_DB: savt_test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    strategy:
      matrix:
        python-version: ["3.13"]

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v4
        with:
          enable-cache: true
          cache-dependency-glob: "uv.lock"

      - name: Set up Python ${{ matrix.python-version }}
        run: uv python install ${{ matrix.python-version }}

      - name: Install the project
        run: uv sync --all-extras --dev

      - name: Run linter
        run: uv tool run ruff check src/ tests/

      - name: Check formatting
        run: uv tool run ruff format src/ tests/ --check

      - name: Run type checker
        run: uv tool run mypy src/

      - name: Run tests
        run: uv run pytest --verbose

      - name: Sanity check terminology settings
        run: |
          echo "Verifying settings in CI..."
          uv run python - <<'PY'
          from src.config import settings
          print('object_name_singular=', settings.object_name_singular)
          print('property_name_singular=', settings.property_name_singular)
          assert settings.object_name_singular == 'pizza', 'Expected OBJECT_NAME_SINGULAR to be pizza'
          PY

      - name: Test server startup
        run: |
          uv run uvicorn src.main:app --host 0.0.0.0 --port 8000 &
          SERVER_PID=$!
          sleep 5
          curl -f http://localhost:8000/ || exit 1
          kill $SERVER_PID
