name: Deploy

on:
  push:
    branches: [main]
    paths-ignore:
      - "README.md"
      - "CLAUDE.md"
      - ".gitignore"

jobs:
  deploy:
    runs-on: ubuntu-latest
    # needs: []  # Add dependency on CI job if you want CI to pass first
    if: github.ref == 'refs/heads/main'

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v4
        with:
          enable-cache: true
          cache-dependency-glob: "uv.lock"

      - name: Set up Python 3.13
        run: uv python install 3.13

      - name: Install the project
        run: uv sync --all-extras

      - name: Build application
        run: |
          echo "Building application..."
          # Add your build steps here if needed
          # For example: uv run python -m build

      # Docker deployment example (uncomment if using Docker)
      # - name: Build Docker image
      #   run: |
      #     docker build -t savt:${{ github.sha }} .
      #     docker tag savt:${{ github.sha }} savt:latest

      # - name: Deploy to production
      #   run: |
      #     echo "Deploying to production..."
      #     # Add your deployment commands here
      #     # Examples:
      #     # - Deploy to cloud provider (AWS, GCP, Azure)
      #     # - Push to container registry
      #     # - Update Kubernetes deployment
      #     # - Deploy to VPS via SSH

      - name: Health check
        run: |
          echo "Deployment completed successfully"
          echo "Server should be accessible at your production URL"
